source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in frontend_scanner.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"

gem "bgit-frontend_auth", path: "../bgit-frontend_auth"

git "https://github.com/content-management-on-rails/cmor.git", branch: "main" do
  gem "cmor", git: "https://github.com/content-management-on-rails/cmor.git"
  gem "cmor-core", git: "https://github.com/content-management-on-rails/cmor.git", glob: "cmor-core/*.gemspec"
  gem "cmor-core-backend", git: "https://github.com/content-management-on-rails/cmor.git", glob: "cmor-core-backend/*.gemspec"
end

gem "authlogic", git: "https://github.com/lsylvester/authlogic", branch: "rails-71"
