source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in bgit_invoicing.gemspec.
gemspec

gem "pg"

gem "sprockets-rails"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"

gem "rails-dummy", github: "robotex82/rails-dummy", branch: "feature/ruby-3-2-compatibility"

git "https://github.com/content-management-on-rails/cmor.git", branch: "main" do
  gem "cmor", git: "https://github.com/content-management-on-rails/cmor.git"
  gem "cmor-core", git: "https://github.com/content-management-on-rails/cmor.git", glob: "cmor-core/*.gemspec"
  gem "cmor-core-backend", git: "https://github.com/content-management-on-rails/cmor.git", glob: "cmor-core-backend/*.gemspec"
end

gem "authlogic", git: "https://github.com/lsylvester/authlogic", branch: "rails-71"

gem "bgit-frontend_auth", path: "../bgit-frontend_auth"
gem "json_seeds-rails", git: "https://github.com/robotex82/json_seeds-rails"
gem "lexoffice_client", git: "https://github.com/beegoodit/lexoffice-ruby"

gem "rao-component", git: "https://github.com/rails-add-ons/rao.git", glob: "rao-component/*.gemspec"
